# Generated by Django 2.2.6 on 2019-10-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('updated_date', models.DateTimeField(verbose_name='date updated')),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=150)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
